apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

images:
- name: goserver
  newName: uillianhenrique/gitops
  newTag: ab450bd39c54a8e36cf30504ceff028241ec0510
