apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

images:
- name: goserver
  newName: uillianhenrique/gitops
  newTag: 2710d9cd5326d7460cf2cfe22a76ecec9b579da0
